CREATE TABLE "staging_zip" (
    ZIP VARCHAR(255) COMPRESSION lz4,
    "TYPE" VARCHAR(255) COMPRESSION lz4,
    DECOMMISSIONED INT,
    PRIMARY_CITY VARCHAR(255) COMPRESSION lz4,
    ACCEPTABLE_CITIES VARCHAR(5000) COMPRESSION lz4,
    UNACCEPTABLE_CITIES VARCHAR(5000) COMPRESSION lz4,
    STATE VARCHAR(255) COMPRESSION lz4,
    COUNTY VARCHAR(255) COMPRESSION lz4,
    TIMEZONE VARCHAR(255) COMPRESSION lz4,
    AREA_CODES VARCHAR(255) COMPRESSION lz4,
    WORLD_REGION VARCHAR(255) COMPRESSION lz4,
    COUNTRY VARCHAR(255) COMPRESSION lz4,
    LATITUDE FLOAT,
    LONGITUDE FLOAT,
    IRS_ESTIMATED_POPULATION_2015 FLOAT
);
CREATE TABLE "cse532.zip" (
    ZIP VARCHAR(255) COMPRESSION lz4,
    STATE VARCHAR(255) COMPRESSION lz4,
    COUNTY VARCHAR(255) COMPRESSION lz4,
    POP FLOAT
);
CREATE INDEX ZIP_IDX ON "cse532.zip" (ZIP);
CREATE INDEX STATE_IDX ON "cse532.zip" (STATE);
CREATE INDEX COUNTY_IDX ON "cse532.zip" (COUNTY);