CREATE INDEX REPORTER_DEA_NO_IDX ON "cse532.dea_ny"  (REPORTER_DEA_NO);

CREATE INDEX REPORTER_STATE_IDX ON "cse532.dea_ny"  (REPORTER_STATE);

CREATE INDEX REPORTER_COUNTY_IDX ON "cse532.dea_ny"  (REPORTER_COUNTY);

CREATE INDEX BUYER_STATE_IDX ON "cse532.dea_ny"  (BUYER_STATE);

CREATE INDEX BUYER_COUNTY_IDX ON "cse532.dea_ny" (BUYER_COUNTY);


