WITH TEMP(TXN_YR, TXN_MNTH) AS (
    SELECT 
    EXTRACT(YEAR FROM TRANSACTION_DATE),
		EXTRACT(MONTH from TRANSACTION_DATE),
        SUM(DOSAGE_UNIT) AS TOTAL_PILLS
    FROM "cse532.dea_ny"
    WHERE BUYER_COUNTY = 'SUFFOLK'
    GROUP BY EXTRACT(YEAR FROM TRANSACTION_DATE), EXTRACT(MONTH from TRANSACTION_DATE)
    ORDER BY EXTRACT(YEAR FROM TRANSACTION_DATE), EXTRACT(MONTH from TRANSACTION_DATE)
)
SELECT 
    CONCAT(TEMP.TXN_YR, ' ', TEMP.TXN_MNTH) as YEAR_MONTH,
    TOTAL_PILLS AS TOTAL_PILLS,
    ROUND(CAST (AVG(TEMP.TOTAL_PILLS) OVER(ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING) AS NUMERIC),2) AS SMOOTHED_PILLS
    FROM
    TEMP
    
    
    