WITH TEMP AS (
    SELECT BUYER_ZIP AS ZIP,
        SUM(MME) AS MME_SUM
    FROM "cse532.dea_ny"
    GROUP BY ZIP
)
SELECT C.ZIP, C.NORMAL_MME FROM (SELECT
    TEMP.ZIP,
    TEMP.MME_SUM/B.POP AS NORMAL_MME
FROM TEMP
    LEFT JOIN "cse532.zip" B ON TEMP.ZIP = B.ZIP
    WHERE B.POP != 0
    ORDER BY (TEMP.MME_SUM/B.POP) DESC)C LIMIT 10;
    
   